/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingMachine;

public class App {

    public static void main(String[] args) {

        Database db = new Database();
        db.setupDB();

        vendingMachine machine = new vendingMachine(db);
        // machine.listOptions("all");
        machine.runVendingMachine();
    }
}
