/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SOFT2412_Assignment2_CC_04_Wed_16_Frank_Gorup;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
