/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SOFT2412_Assignment2_CC_04_Wed_16_Frank_Gorup;

public class App {

    public static void main(String[] args) {
        vendingMachine machine = new vendingMachine();
        machine.listOptions("all");
    }
}
