/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SOFT2412_Assignment2_CC_04_Wed_16_Frank_Gorup;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
